/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniproject;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author USER
 */
public class update extends javax.swing.JFrame {

    /**
     * Creates new form details
     */
    public update() {
        initComponents();
        usermethod();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nametext = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        yeartext = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rollnotext = new javax.swing.JTextField();
        degreetext = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        departmenttext = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fathertext = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        gendertext = new javax.swing.JTextField();
        no1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        no2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        yearstext = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        entry = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        exit = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        section = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        dob = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        mother = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 0, 204));
        jPanel1.setLayout(null);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(100, 70, 330, 20);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Update address");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(550, 160, 130, 25);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 280, 60, 20);

        nametext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametextActionPerformed(evt);
            }
        });
        jPanel1.add(nametext);
        nametext.setBounds(95, 278, 150, 20);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Year");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 338, 38, 25);
        jPanel1.add(yeartext);
        yeartext.setBounds(60, 340, 55, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Father name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(290, 340, 79, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Degree");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(470, 310, 52, 17);

        rollnotext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollnotextActionPerformed(evt);
            }
        });
        jPanel1.add(rollnotext);
        rollnotext.setBounds(330, 280, 111, 20);

        degreetext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degreetextActionPerformed(evt);
            }
        });
        jPanel1.add(degreetext);
        degreetext.setBounds(530, 310, 40, 20);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Department");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(480, 280, 74, 17);
        jPanel1.add(departmenttext);
        departmenttext.setBounds(570, 280, 193, 20);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Contact no 1:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 370, 83, 20);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Roll no");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(24, 70, 44, 17);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Roll no");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(270, 280, 44, 17);

        fathertext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fathertextActionPerformed(evt);
            }
        });
        jPanel1.add(fathertext);
        fathertext.setBounds(380, 340, 130, 20);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel9.setText("Update details");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(270, 16, 211, 42);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("gender");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(610, 310, 42, 17);

        gendertext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gendertextActionPerformed(evt);
            }
        });
        jPanel1.add(gendertext);
        gendertext.setBounds(680, 310, 79, 20);
        jPanel1.add(no1);
        no1.setBounds(110, 370, 118, 20);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Contact no 2:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(250, 370, 83, 17);
        jPanel1.add(no2);
        no2.setBounds(340, 370, 120, 20);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Address");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 406, 74, 20);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("Roll no");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(20, 190, 68, 63);

        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(100, 210, 330, 20);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("Delete student");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(550, 210, 130, 25);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("Address");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(20, 100, 49, 17);

        area.setColumns(20);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(100, 100, 330, 100);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("Update years");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(550, 110, 130, 25);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel15.setText("Years");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(520, 70, 30, 20);
        jPanel1.add(yearstext);
        yearstext.setBounds(570, 70, 104, 20);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Entry Year");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(20, 308, 68, 17);
        jPanel1.add(entry);
        entry.setBounds(98, 307, 60, 30);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setText("Exit Year");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(180, 310, 58, 17);
        jPanel1.add(exit);
        exit.setBounds(260, 310, 50, 20);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel19.setText("Section");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(340, 310, 45, 17);
        jPanel1.add(section);
        section.setBounds(400, 310, 40, 20);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel20.setText("DOB");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(140, 343, 26, 20);

        dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobActionPerformed(evt);
            }
        });
        jPanel1.add(dob);
        dob.setBounds(180, 340, 90, 20);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setText("Mother name");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(530, 340, 83, 17);
        jPanel1.add(mother);
        mother.setBounds(640, 340, 120, 20);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setText("email id");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(480, 370, 49, 17);

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email);
        email.setBounds(550, 370, 210, 20);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel23.setText("New student details");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(220, 240, 300, 30);

        address.setColumns(20);
        address.setRows(5);
        jScrollPane2.setViewportView(address);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(100, 400, 260, 100);

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setText("Insert");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(560, 430, 130, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            String s=area.getText();
            Connection c;
            c=DriverManager.getConnection("jdbc:derby://localhost:1527/ABSENTEES_DATABASE");
            Statement st=c.createStatement();
            String b=jComboBox1.getItemAt(jComboBox1.getSelectedIndex());
            st.executeUpdate("Update database set address='"+s+"' where id='"+b+"' ");
            area.setText("");
            
        }catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void degreetextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degreetextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_degreetextActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void rollnotextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollnotextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rollnotextActionPerformed

    private void nametextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametextActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try
        {
            Connection c;
            jComboBox1.removeAllItems();
            c=DriverManager.getConnection("jdbc:derby://localhost:1527/ABSENTEES_DATABASE");
            Statement st=c.createStatement();
            String str=jComboBox2.getItemAt(jComboBox2.getSelectedIndex());
            st.executeUpdate("Delete from database where id='"+str+"'");
            usermethod();
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try
        {
            String s=yearstext.getText();
            Connection c;
            c=DriverManager.getConnection("jdbc:derby://localhost:1527/ABSENTEES_DATABASE");
            Statement st=c.createStatement();
            String b=jComboBox1.getItemAt(jComboBox1.getSelectedIndex());
            st.executeUpdate("Update database set years='"+s+"' where id='"+b+"' ");
            yearstext.setText("");
            
        }catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void fathertextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fathertextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fathertextActionPerformed

    private void gendertextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gendertextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gendertextActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String s1=nametext.getText();
        String s2=fathertext.getText();
        String s3=degreetext.getText();
        String s4=yeartext.getText();
        String s5=departmenttext.getText();
        String s7=rollnotext.getText();
        String s8=gendertext.getText();
        String s6=mother.getText();
        String s9=no2.getText();
        String s10=no1.getText();
        String s11=entry.getText();
        String s12=exit.getText();
        String s13=section.getText();
        String s14=dob.getText();
        String s15=email.getText();
        String s16=address.getText();
        try
        {
            Connection c;
            c=DriverManager.getConnection("jdbc:derby://localhost:1527/ABSENTEES_DATABASE");
            Statement st=c.createStatement();
            st.executeUpdate("insert into database values('"+s7+"','"+s1+"','"+s5+"','"+s11+"','"+s12+"','"+s13+"','"+s8+"','"+s14+"','"+s2+"','"+s6+"','"+s9+"','"+s10+"','"+s15+"','"+s16+"','"+s3+"','"+s4+"')");
            usermethod();
            entry.setText("");
            exit.setText("");
            section.setText("");
            dob.setText("");
            email.setText("");
            address.setText("");
            nametext.setText("");
            rollnotext.setText("");
            degreetext.setText("");
            departmenttext.setText("");
            fathertext.setText("");
            no1.setText("");
            no2.setText("");
            yeartext.setText("");
            gendertext.setText("");
            mother.setText("");
        }catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    public void usermethod()
    {
        try
        {
            Connection c;
            jComboBox1.removeAllItems();
            jComboBox2.removeAllItems();
            c=DriverManager.getConnection("jdbc:derby://localhost:1527/ABSENTEES_DATABASE");
            Statement st=c.createStatement();
            ResultSet rs=st.executeQuery("Select id from database");
            while(rs.next())
            {
                jComboBox1.addItem(rs.getString("id"));
                jComboBox2.addItem(rs.getString("id"));
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JTextArea area;
    private javax.swing.JTextField degreetext;
    private javax.swing.JTextField departmenttext;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField email;
    private javax.swing.JTextField entry;
    private javax.swing.JTextField exit;
    private javax.swing.JTextField fathertext;
    private javax.swing.JTextField gendertext;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mother;
    private javax.swing.JTextField nametext;
    private javax.swing.JTextField no1;
    private javax.swing.JTextField no2;
    private javax.swing.JTextField rollnotext;
    private javax.swing.JTextField section;
    private javax.swing.JTextField yearstext;
    private javax.swing.JTextField yeartext;
    // End of variables declaration//GEN-END:variables
}